window.VOCAB_DATA = {
  a1: {
    title: "A1 · Beginner",
    desc: "Everyday words for greetings, family, food, and daily routines.",
    words: [
      {w:"hello",p:"interjection",ipa:"/həˈloʊ/",def:"A greeting used when meeting someone.",ex:"She waved and said hello to her neighbor."},
      {w:"name",p:"noun",ipa:"/neɪm/",def:"What a person or thing is called.",ex:"My name is Fazliddin."},
      {w:"family",p:"noun",ipa:"/ˈfæməli/",def:"A group of people related to each other.",ex:"We have dinner with my family every Sunday."},
      {w:"friend",p:"noun",ipa:"/frɛnd/",def:"A person you know well and like.",ex:"He is my best friend from school."},
      {w:"house",p:"noun",ipa:"/haʊs/",def:"A building where people live.",ex:"They bought a small house near the park."},
      {w:"water",p:"noun",ipa:"/ˈwɔːtər/",def:"A clear liquid people drink.",ex:"Please drink more water every day."},
      {w:"food",p:"noun",ipa:"/fuːd/",def:"Anything people eat to live.",ex:"The food at that restaurant is delicious."},
      {w:"eat",p:"verb",ipa:"/iːt/",def:"To put food in your mouth and swallow it.",ex:"We usually eat breakfast at seven."},
      {w:"drink",p:"verb",ipa:"/drɪŋk/",def:"To take liquid into your mouth and swallow it.",ex:"He likes to drink coffee in the morning."},
      {w:"sleep",p:"verb",ipa:"/sliːp/",def:"To rest with your eyes closed at night.",ex:"Children need to sleep at least nine hours."},
      {w:"go",p:"verb",ipa:"/goʊ/",def:"To move from one place to another.",ex:"Let's go to the market together."},
      {w:"come",p:"verb",ipa:"/kʌm/",def:"To move toward the speaker or a place.",ex:"Please come to my house tomorrow."},
      {w:"big",p:"adjective",ipa:"/bɪg/",def:"Large in size.",ex:"They live in a big apartment downtown."},
      {w:"small",p:"adjective",ipa:"/smɔːl/",def:"Little in size.",ex:"She keeps a small notebook in her bag."},
      {w:"happy",p:"adjective",ipa:"/ˈhæpi/",def:"Feeling or showing pleasure.",ex:"He looked happy after the good news."},
      {w:"sad",p:"adjective",ipa:"/sæd/",def:"Feeling unhappy or sorrow.",ex:"She felt sad when her trip was cancelled."},
      {w:"day",p:"noun",ipa:"/deɪ/",def:"A period of twenty-four hours.",ex:"I work five days a week."},
      {w:"night",p:"noun",ipa:"/naɪt/",def:"The dark hours between evening and morning.",ex:"We watched the stars at night."},
      {w:"school",p:"noun",ipa:"/skuːl/",def:"A place where children go to learn.",ex:"My daughter walks to school every morning."},
      {w:"work",p:"noun",ipa:"/wɜːrk/",def:"An activity done to earn money or achieve a result.",ex:"He goes to work by bus."},
      {w:"time",p:"noun",ipa:"/taɪm/",def:"A period during which something happens.",ex:"Do you have time to talk now?"},
      {w:"money",p:"noun",ipa:"/ˈmʌni/",def:"Coins or notes used to buy things.",ex:"She saved money to buy a new phone."},
      {w:"book",p:"noun",ipa:"/bʊk/",def:"A set of printed pages joined together to read.",ex:"He reads a book before bed every night."},
      {w:"open",p:"verb",ipa:"/ˈoʊpən/",def:"To make something no longer closed.",ex:"Please open the window; it's hot in here."},
      {w:"close",p:"verb",ipa:"/kloʊz/",def:"To shut something.",ex:"Can you close the door behind you?"},
      {w:"buy",p:"verb",ipa:"/baɪ/",def:"To get something by paying money for it.",ex:"I need to buy some bread on the way home."},
      {w:"today",p:"adverb",ipa:"/təˈdeɪ/",def:"On this present day.",ex:"We are meeting our teacher today."},
      {w:"tomorrow",p:"adverb",ipa:"/təˈmɔːroʊ/",def:"On the day after today.",ex:"The exam is tomorrow morning."},
      {w:"weather",p:"noun",ipa:"/ˈwɛðər/",def:"The condition of the sky and temperature outside.",ex:"The weather is very cold this week."},
      {w:"color",p:"noun",ipa:"/ˈkʌlər/",def:"A visual property like red, blue, or green.",ex:"What color do you like the most?"}
    ]
  },
  a2: {
    title: "A2 · Elementary",
    desc: "Shopping, travel, hobbies, and simple opinions.",
    words: [
      {w:"order",p:"verb",ipa:"/ˈɔːrdər/",def:"To ask for food or a product to be brought or sent.",ex:"We ordered pizza for dinner."},
      {w:"price",p:"noun",ipa:"/praɪs/",def:"The amount of money needed to buy something.",ex:"The price of the ticket went up last month."},
      {w:"cheap",p:"adjective",ipa:"/tʃiːp/",def:"Costing little money.",ex:"This market sells cheap vegetables."},
      {w:"expensive",p:"adjective",ipa:"/ɪkˈspɛnsɪv/",def:"Costing a lot of money.",ex:"That watch looks expensive."},
      {w:"travel",p:"verb",ipa:"/ˈtrævəl/",def:"To go from one place to another, often far away.",ex:"They love to travel during summer vacation."},
      {w:"airport",p:"noun",ipa:"/ˈɛərpɔːrt/",def:"A place where planes take off and land.",ex:"We arrived at the airport two hours early."},
      {w:"ticket",p:"noun",ipa:"/ˈtɪkɪt/",def:"A piece of paper or code showing you paid to enter or ride.",ex:"I already booked our train tickets."},
      {w:"hotel",p:"noun",ipa:"/hoʊˈtɛl/",def:"A building where travelers pay to stay.",ex:"Our hotel room had a nice view of the sea."},
      {w:"menu",p:"noun",ipa:"/ˈmɛnjuː/",def:"A list of food available in a restaurant.",ex:"Can I see the menu, please?"},
      {w:"hobby",p:"noun",ipa:"/ˈhɒbi/",def:"An activity done for pleasure in free time.",ex:"Her hobby is painting landscapes."},
      {w:"weekend",p:"noun",ipa:"/ˈwiːkɛnd/",def:"Saturday and Sunday.",ex:"We usually visit my parents on the weekend."},
      {w:"holiday",p:"noun",ipa:"/ˈhɒlədeɪ/",def:"A day or period of rest from work or school.",ex:"They went to the mountains for the holiday."},
      {w:"plan",p:"verb",ipa:"/plæn/",def:"To decide what to do in advance.",ex:"We are planning a trip to Busan."},
      {w:"meeting",p:"noun",ipa:"/ˈmiːtɪŋ/",def:"An event where people come together to discuss something.",ex:"The team has a meeting every Monday."},
      {w:"appointment",p:"noun",ipa:"/əˈpɔɪntmənt/",def:"An arranged time to meet someone, often for business or health.",ex:"I have a dentist appointment tomorrow."},
      {w:"hospital",p:"noun",ipa:"/ˈhɒspɪtl/",def:"A place where sick or injured people are treated.",ex:"He was taken to the hospital after the accident."},
      {w:"medicine",p:"noun",ipa:"/ˈmɛdɪsɪn/",def:"A substance used to treat illness.",ex:"Take this medicine twice a day."},
      {w:"healthy",p:"adjective",ipa:"/ˈhɛlθi/",def:"Being in good physical condition.",ex:"Eating vegetables keeps you healthy."},
      {w:"exercise",p:"noun",ipa:"/ˈɛksərsaɪz/",def:"Physical activity done to stay fit.",ex:"She does exercise every morning before work."},
      {w:"neighbor",p:"noun",ipa:"/ˈneɪbər/",def:"A person who lives near you.",ex:"My neighbor helped me carry the boxes."},
      {w:"furniture",p:"noun",ipa:"/ˈfɜːrnɪtʃər/",def:"Movable items like tables and chairs used in a room.",ex:"We bought new furniture for the living room."},
      {w:"borrow",p:"verb",ipa:"/ˈbɒroʊ/",def:"To take something with a plan to return it.",ex:"Can I borrow your pen for a moment?"},
      {w:"lend",p:"verb",ipa:"/lɛnd/",def:"To give something temporarily, expecting it back.",ex:"He lent me his umbrella yesterday."},
      {w:"arrive",p:"verb",ipa:"/əˈraɪv/",def:"To reach a place.",ex:"The bus arrives at nine o'clock."},
      {w:"leave",p:"verb",ipa:"/liːv/",def:"To go away from a place.",ex:"We need to leave before it gets dark."},
      {w:"remember",p:"verb",ipa:"/rɪˈmɛmbər/",def:"To keep something in your memory.",ex:"I can't remember where I put my keys."},
      {w:"forget",p:"verb",ipa:"/fərˈgɛt/",def:"To fail to remember something.",ex:"Don't forget to lock the door."},
      {w:"invite",p:"verb",ipa:"/ɪnˈvaɪt/",def:"To ask someone to come to an event.",ex:"They invited us to their wedding."},
      {w:"comfortable",p:"adjective",ipa:"/ˈkʌmftərbəl/",def:"Giving a pleasant feeling of physical ease.",ex:"This chair is very comfortable."},
      {w:"crowded",p:"adjective",ipa:"/ˈkraʊdɪd/",def:"Full of people.",ex:"The subway was crowded during rush hour."}
    ]
  },
  b1: {
    title: "B1 · Intermediate",
    desc: "Opinions, feelings, relationships, and work topics.",
    words: [
      {w:"opinion",p:"noun",ipa:"/əˈpɪnjən/",def:"A personal view or judgment about something.",ex:"In my opinion, the plan needs more time."},
      {w:"experience",p:"noun",ipa:"/ɪkˈspɪəriəns/",def:"Knowledge or skill gained from doing something.",ex:"She has five years of experience in marketing."},
      {w:"environment",p:"noun",ipa:"/ɪnˈvaɪərənmənt/",def:"The natural world, or the surroundings someone lives in.",ex:"We should protect the environment for future generations."},
      {w:"recycle",p:"verb",ipa:"/riːˈsaɪkəl/",def:"To process used materials so they can be used again.",ex:"Please recycle the plastic bottles."},
      {w:"technology",p:"noun",ipa:"/tɛkˈnɒlədʒi/",def:"The application of science to solve practical problems.",ex:"New technology has changed how we communicate."},
      {w:"communicate",p:"verb",ipa:"/kəˈmjuːnɪkeɪt/",def:"To share information or ideas with others.",ex:"It's important to communicate clearly at work."},
      {w:"relationship",p:"noun",ipa:"/rɪˈleɪʃənʃɪp/",def:"The way two or more people are connected.",ex:"They have a strong relationship built on trust."},
      {w:"argument",p:"noun",ipa:"/ˈɑːrgjumənt/",def:"A disagreement or reasoned point in a discussion.",ex:"They had an argument about money."},
      {w:"decision",p:"noun",ipa:"/dɪˈsɪʒən/",def:"A choice made after thinking about options.",ex:"It was a difficult decision to change jobs."},
      {w:"responsibility",p:"noun",ipa:"/rɪˌspɒnsəˈbɪləti/",def:"A duty to deal with something.",ex:"Taking care of the project is her responsibility."},
      {w:"achievement",p:"noun",ipa:"/əˈtʃiːvmənt/",def:"Something accomplished successfully through effort.",ex:"Graduating early was a big achievement for him."},
      {w:"challenge",p:"noun",ipa:"/ˈtʃælɪndʒ/",def:"A difficult task that tests someone's ability.",ex:"Learning a new language is a real challenge."},
      {w:"opportunity",p:"noun",ipa:"/ˌɒpərˈtjuːnəti/",def:"A chance to do something.",ex:"This job is a great opportunity for her career."},
      {w:"confident",p:"adjective",ipa:"/ˈkɒnfɪdənt/",def:"Feeling sure about one's abilities or ideas.",ex:"He felt confident before the interview."},
      {w:"nervous",p:"adjective",ipa:"/ˈnɜːrvəs/",def:"Worried or anxious about something.",ex:"She was nervous before the exam."},
      {w:"disappointed",p:"adjective",ipa:"/ˌdɪsəˈpɔɪntɪd/",def:"Feeling sad because something did not happen as hoped.",ex:"He was disappointed with his test score."},
      {w:"curious",p:"adjective",ipa:"/ˈkjʊəriəs/",def:"Eager to know or learn something.",ex:"The child was curious about how the machine worked."},
      {w:"generous",p:"adjective",ipa:"/ˈdʒɛnərəs/",def:"Willing to give more than expected.",ex:"She is generous with her time and money."},
      {w:"honest",p:"adjective",ipa:"/ˈɒnɪst/",def:"Telling the truth and not deceiving others.",ex:"He gave an honest answer to the question."},
      {w:"patient",p:"adjective",ipa:"/ˈpeɪʃənt/",def:"Able to wait calmly without complaint.",ex:"Be patient; the results will take time."},
      {w:"stubborn",p:"adjective",ipa:"/ˈstʌbərn/",def:"Refusing to change one's mind.",ex:"He is too stubborn to admit he was wrong."},
      {w:"ambitious",p:"adjective",ipa:"/æmˈbɪʃəs/",def:"Having a strong desire to succeed.",ex:"She is ambitious and wants to start her own company."},
      {w:"career",p:"noun",ipa:"/kəˈrɪər/",def:"The jobs someone has over their working life.",ex:"He built a successful career in engineering."},
      {w:"promotion",p:"noun",ipa:"/prəˈmoʊʃən/",def:"A move to a higher position at work.",ex:"She got a promotion after two years."},
      {w:"colleague",p:"noun",ipa:"/ˈkɒliːg/",def:"A person you work with.",ex:"My colleague helped me finish the report."},
      {w:"deadline",p:"noun",ipa:"/ˈdɛdlaɪn/",def:"The latest time by which something must be done.",ex:"The deadline for the project is Friday."},
      {w:"negotiate",p:"verb",ipa:"/nɪˈgoʊʃieɪt/",def:"To discuss something to reach an agreement.",ex:"They negotiated a better price for the car."},
      {w:"reliable",p:"adjective",ipa:"/rɪˈlaɪəbəl/",def:"Able to be trusted to do what is expected.",ex:"He is a reliable employee who is never late."},
      {w:"flexible",p:"adjective",ipa:"/ˈflɛksəbəl/",def:"Able to change or adapt easily.",ex:"My work schedule is flexible."},
      {w:"achieve",p:"verb",ipa:"/əˈtʃiːv/",def:"To successfully complete or reach a goal.",ex:"She worked hard to achieve her dream."}
    ]
  },
  b2: {
    title: "B2 · Upper Intermediate",
    desc: "Abstract ideas, argument, and analytical vocabulary.",
    words: [
      {w:"consequence",p:"noun",ipa:"/ˈkɒnsɪkwəns/",def:"A result or effect of an action.",ex:"Missing the deadline had serious consequences."},
      {w:"controversial",p:"adjective",ipa:"/ˌkɒntrəˈvɜːrʃəl/",def:"Causing disagreement or argument.",ex:"The new policy is quite controversial."},
      {w:"significant",p:"adjective",ipa:"/sɪgˈnɪfɪkənt/",def:"Important or notable enough to have an effect.",ex:"There was a significant increase in sales."},
      {w:"phenomenon",p:"noun",ipa:"/fəˈnɒmɪnən/",def:"A fact or event that is observed to happen.",ex:"Climate change is a global phenomenon."},
      {w:"perspective",p:"noun",ipa:"/pərˈspɛktɪv/",def:"A particular way of viewing or thinking about something.",ex:"Try to see the issue from her perspective."},
      {w:"assumption",p:"noun",ipa:"/əˈsʌmpʃən/",def:"Something believed to be true without proof.",ex:"We made an assumption that the store would be open."},
      {w:"contradict",p:"verb",ipa:"/ˌkɒntrəˈdɪkt/",def:"To say something that is opposite to another statement.",ex:"His answer seemed to contradict what he said earlier."},
      {w:"justify",p:"verb",ipa:"/ˈdʒʌstɪfaɪ/",def:"To give a good reason for an action or decision.",ex:"She justified her choice with strong evidence."},
      {w:"emphasize",p:"verb",ipa:"/ˈɛmfəsaɪz/",def:"To give special importance to something.",ex:"The teacher emphasized the importance of practice."},
      {w:"exaggerate",p:"verb",ipa:"/ɪgˈzædʒəreɪt/",def:"To describe something as bigger or better than it really is.",ex:"He tends to exaggerate his achievements."},
      {w:"sustainable",p:"adjective",ipa:"/səˈsteɪnəbəl/",def:"Able to continue over time without harming resources.",ex:"The company invests in sustainable energy."},
      {w:"innovative",p:"adjective",ipa:"/ˈɪnəveɪtɪv/",def:"Introducing new ideas or methods.",ex:"Their innovative design won an award."},
      {w:"efficient",p:"adjective",ipa:"/ɪˈfɪʃənt/",def:"Working well without wasting time or resources.",ex:"The new system is more efficient than the old one."},
      {w:"versatile",p:"adjective",ipa:"/ˈvɜːrsətaɪl/",def:"Able to adapt to many different functions or activities.",ex:"She is a versatile actor who can play many roles."},
      {w:"ambiguous",p:"adjective",ipa:"/æmˈbɪgjuəs/",def:"Open to more than one interpretation.",ex:"His answer was ambiguous and confused everyone."},
      {w:"comprehensive",p:"adjective",ipa:"/ˌkɒmprɪˈhɛnsɪv/",def:"Complete and including everything necessary.",ex:"The report gives a comprehensive overview of the market."},
      {w:"inevitable",p:"adjective",ipa:"/ɪnˈɛvɪtəbəl/",def:"Certain to happen; unavoidable.",ex:"Change was inevitable as the company grew."},
      {w:"subsequent",p:"adjective",ipa:"/ˈsʌbsɪkwənt/",def:"Coming after something in time.",ex:"Subsequent meetings will cover the budget."},
      {w:"notion",p:"noun",ipa:"/ˈnoʊʃən/",def:"An idea or belief about something.",ex:"He rejected the notion that success requires luck."},
      {w:"tendency",p:"noun",ipa:"/ˈtɛndənsi/",def:"A likelihood to behave in a particular way.",ex:"She has a tendency to work late."},
      {w:"distinguish",p:"verb",ipa:"/dɪˈstɪŋgwɪʃ/",def:"To recognize the difference between two things.",ex:"It can be hard to distinguish the twins."},
      {w:"undermine",p:"verb",ipa:"/ˌʌndərˈmaɪn/",def:"To weaken something gradually.",ex:"Constant criticism can undermine someone's confidence."},
      {w:"reinforce",p:"verb",ipa:"/ˌriːɪnˈfɔːrs/",def:"To strengthen or support something.",ex:"The results reinforce our original theory."},
      {w:"prioritize",p:"verb",ipa:"/praɪˈɒrɪtaɪz/",def:"To treat something as more important than other things.",ex:"You need to prioritize your tasks this week."},
      {w:"compromise",p:"noun",ipa:"/ˈkɒmprəmaɪz/",def:"An agreement reached by each side giving up something.",ex:"They reached a compromise after long discussions."},
      {w:"initiative",p:"noun",ipa:"/ɪˈnɪʃətɪv/",def:"The ability to act independently, or a new plan.",ex:"She showed great initiative by starting the project herself."},
      {w:"integrity",p:"noun",ipa:"/ɪnˈtɛgrəti/",def:"The quality of being honest and having strong moral principles.",ex:"He is respected for his integrity."},
      {w:"resilience",p:"noun",ipa:"/rɪˈzɪliəns/",def:"The ability to recover quickly from difficulties.",ex:"Her resilience helped her overcome many setbacks."},
      {w:"empathy",p:"noun",ipa:"/ˈɛmpəθi/",def:"The ability to understand another person's feelings.",ex:"Good leaders show empathy toward their team."},
      {w:"diverse",p:"adjective",ipa:"/daɪˈvɜːrs/",def:"Showing a variety of different types or forms.",ex:"The company has a diverse workforce."}
    ]
  },
  c1: {
    title: "C1 · Advanced",
    desc: "Nuanced, precise vocabulary for formal and academic contexts.",
    words: [
      {w:"nuanced",p:"adjective",ipa:"/ˈnjuːɑːnst/",def:"Characterized by subtle differences in meaning or tone.",ex:"Her analysis offered a nuanced view of the issue."},
      {w:"paradox",p:"noun",ipa:"/ˈpærədɒks/",def:"A statement that seems contradictory but may be true.",ex:"It's a paradox that saving time often takes more planning."},
      {w:"discrepancy",p:"noun",ipa:"/dɪˈskrɛpənsi/",def:"A difference between things that should match.",ex:"There is a discrepancy between the two reports."},
      {w:"mitigate",p:"verb",ipa:"/ˈmɪtɪgeɪt/",def:"To make something less severe or serious.",ex:"The new policy aims to mitigate flood damage."},
      {w:"corroborate",p:"verb",ipa:"/kəˈrɒbəreɪt/",def:"To confirm or support a statement with evidence.",ex:"Witnesses corroborated her account of the event."},
      {w:"ubiquitous",p:"adjective",ipa:"/juːˈbɪkwɪtəs/",def:"Present or found everywhere.",ex:"Smartphones have become ubiquitous in modern life."},
      {w:"meticulous",p:"adjective",ipa:"/məˈtɪkjələs/",def:"Showing great attention to detail.",ex:"She is meticulous about checking her work."},
      {w:"pragmatic",p:"adjective",ipa:"/prægˈmætɪk/",def:"Dealing with things in a practical, sensible way.",ex:"He took a pragmatic approach to solving the problem."},
      {w:"arbitrary",p:"adjective",ipa:"/ˈɑːrbɪtreri/",def:"Based on random choice rather than reason.",ex:"The rule seemed arbitrary and unfair."},
      {w:"coherent",p:"adjective",ipa:"/koʊˈhɪərənt/",def:"Logical and consistent; easy to follow.",ex:"He gave a coherent explanation of the plan."},
      {w:"plausible",p:"adjective",ipa:"/ˈplɔːzəbəl/",def:"Seeming reasonable or probable.",ex:"Her excuse sounded plausible."},
      {w:"subtle",p:"adjective",ipa:"/ˈsʌtəl/",def:"Not obvious; delicate or precise.",ex:"There was a subtle change in his tone."},
      {w:"deteriorate",p:"verb",ipa:"/dɪˈtɪəriəreɪt/",def:"To become progressively worse.",ex:"Relations between the two countries deteriorated."},
      {w:"alleviate",p:"verb",ipa:"/əˈliːvieɪt/",def:"To make suffering or a problem less severe.",ex:"The medicine helped alleviate the pain."},
      {w:"ambivalent",p:"adjective",ipa:"/æmˈbɪvələnt/",def:"Having mixed feelings about something.",ex:"She felt ambivalent about accepting the offer."},
      {w:"articulate",p:"verb",ipa:"/ɑːrˈtɪkjəleɪt/",def:"To express thoughts or feelings clearly.",ex:"He struggled to articulate his concerns."},
      {w:"cognizant",p:"adjective",ipa:"/ˈkɒgnɪzənt/",def:"Aware of or informed about something.",ex:"She was cognizant of the risks involved."},
      {w:"elicit",p:"verb",ipa:"/ɪˈlɪsɪt/",def:"To draw out a response or piece of information.",ex:"The survey was designed to elicit honest feedback."},
      {w:"facilitate",p:"verb",ipa:"/fəˈsɪlɪteɪt/",def:"To make an action or process easier.",ex:"The new software facilitates faster data analysis."},
      {w:"implicit",p:"adjective",ipa:"/ɪmˈplɪsɪt/",def:"Suggested without being directly stated.",ex:"There was an implicit warning in his tone."},
      {w:"inherent",p:"adjective",ipa:"/ɪnˈhɪərənt/",def:"Existing as a natural or basic part of something.",ex:"There are inherent risks in any investment."},
      {w:"notwithstanding",p:"preposition",ipa:"/ˌnɒtwɪθˈstændɪŋ/",def:"In spite of; despite.",ex:"Notwithstanding the delays, the project finished on time."},
      {w:"precarious",p:"adjective",ipa:"/prɪˈkɛəriəs/",def:"Not securely held or in a dangerous position.",ex:"The company was in a precarious financial situation."},
      {w:"redundant",p:"adjective",ipa:"/rɪˈdʌndənt/",def:"No longer needed; unnecessarily repetitive.",ex:"Some of the wording in the contract was redundant."},
      {w:"tangible",p:"adjective",ipa:"/ˈtændʒəbəl/",def:"Clear and definite; able to be perceived as real.",ex:"The project produced tangible results within a year."},
      {w:"unprecedented",p:"adjective",ipa:"/ʌnˈprɛsɪdɛntɪd/",def:"Never having happened before.",ex:"The company saw unprecedented growth last year."},
      {w:"vindicate",p:"verb",ipa:"/ˈvɪndɪkeɪt/",def:"To clear someone of blame after being proven right.",ex:"The results eventually vindicated her decision."},
      {w:"volatile",p:"adjective",ipa:"/ˈvɒlətaɪl/",def:"Likely to change quickly and unpredictably.",ex:"The stock market has been volatile this month."},
      {w:"discern",p:"verb",ipa:"/dɪˈsɜːrn/",def:"To perceive or recognize something not immediately obvious.",ex:"It was hard to discern his true intentions."},
      {w:"deference",p:"noun",ipa:"/ˈdɛfərəns/",def:"Respectful submission to someone's wishes or judgment.",ex:"He spoke with deference to his mentor's opinion."}
    ]
  },
  c2: {
    title: "C2 · Proficiency",
    desc: "Rare, precise, and literary vocabulary for near-native command.",
    words: [
      {w:"erudite",p:"adjective",ipa:"/ˈɛrʊdaɪt/",def:"Having or showing great knowledge from study.",ex:"His erudite lecture impressed the whole department."},
      {w:"ephemeral",p:"adjective",ipa:"/ɪˈfɛmərəl/",def:"Lasting for a very short time.",ex:"Fame in that industry can be ephemeral."},
      {w:"cacophony",p:"noun",ipa:"/kəˈkɒfəni/",def:"A harsh mixture of unpleasant sounds.",ex:"The street was filled with the cacophony of traffic."},
      {w:"ineffable",p:"adjective",ipa:"/ɪnˈɛfəbəl/",def:"Too great to be expressed in words.",ex:"She described an ineffable sense of joy."},
      {w:"perfunctory",p:"adjective",ipa:"/pərˈfʌŋktəri/",def:"Done with minimal effort, as a mere formality.",ex:"He gave a perfunctory nod and walked away."},
      {w:"obfuscate",p:"verb",ipa:"/ˈɒbfəskeɪt/",def:"To deliberately make something unclear or confusing.",ex:"The report seemed designed to obfuscate the real costs."},
      {w:"sycophant",p:"noun",ipa:"/ˈsɪkəfænt/",def:"A person who flatters others to gain advantage.",ex:"He was surrounded by sycophants who never disagreed with him."},
      {w:"quintessential",p:"adjective",ipa:"/ˌkwɪntɪˈsɛnʃəl/",def:"Representing the most perfect example of a quality.",ex:"The small café was the quintessential Parisian experience."},
      {w:"vicissitude",p:"noun",ipa:"/vɪˈsɪsɪtjuːd/",def:"A change of circumstances, often difficult, in life.",ex:"He faced the vicissitudes of his career with patience."},
      {w:"capricious",p:"adjective",ipa:"/kəˈprɪʃəs/",def:"Given to sudden, unpredictable changes in mood or behavior.",ex:"The weather in the mountains can be capricious."},
      {w:"deleterious",p:"adjective",ipa:"/ˌdɛləˈtɪəriəs/",def:"Causing harm or damage.",ex:"Smoking has deleterious effects on health."},
      {w:"egregious",p:"adjective",ipa:"/ɪˈgriːdʒiəs/",def:"Outstandingly bad; shocking.",ex:"It was an egregious error that cost them the contract."},
      {w:"fastidious",p:"adjective",ipa:"/fæˈstɪdiəs/",def:"Very attentive to detail and hard to please.",ex:"She is fastidious about keeping her desk organized."},
      {w:"garrulous",p:"adjective",ipa:"/ˈgærələs/",def:"Excessively talkative, especially about trivial matters.",ex:"The garrulous taxi driver talked the whole ride."},
      {w:"iconoclast",p:"noun",ipa:"/aɪˈkɒnəklæst/",def:"A person who challenges established beliefs or traditions.",ex:"The artist was known as an iconoclast in her field."},
      {w:"juxtapose",p:"verb",ipa:"/ˈdʒʌkstəpoʊz/",def:"To place two things side by side to compare them.",ex:"The exhibit juxtaposes old photographs with modern art."},
      {w:"laconic",p:"adjective",ipa:"/ləˈkɒnɪk/",def:"Using very few words; concise to the point of terseness.",ex:"His laconic reply gave nothing away."},
      {w:"magnanimous",p:"adjective",ipa:"/mægˈnænɪməs/",def:"Generous or forgiving, especially toward a rival.",ex:"She was magnanimous in victory, praising her opponent."},
      {w:"nebulous",p:"adjective",ipa:"/ˈnɛbjələs/",def:"Vague or unclear in form or meaning.",ex:"His plans for the future remained nebulous."},
      {w:"obstinate",p:"adjective",ipa:"/ˈɒbstɪnət/",def:"Stubbornly refusing to change one's opinion.",ex:"He was obstinate and would not consider other options."},
      {w:"paradigm",p:"noun",ipa:"/ˈpærədaɪm/",def:"A typical example or pattern of something.",ex:"The discovery represented a new paradigm in medicine."},
      {w:"quixotic",p:"adjective",ipa:"/kwɪkˈsɒtɪk/",def:"Extremely idealistic and unrealistic.",ex:"His quixotic plan to reform the industry alone failed."},
      {w:"recalcitrant",p:"adjective",ipa:"/rɪˈkælsɪtrənt/",def:"Stubbornly resistant to authority or guidance.",ex:"The recalcitrant committee refused to approve the budget."},
      {w:"sanguine",p:"adjective",ipa:"/ˈsæŋgwɪn/",def:"Optimistic, especially in a difficult situation.",ex:"She remained sanguine despite the setbacks."},
      {w:"taciturn",p:"adjective",ipa:"/ˈtæsɪtɜːrn/",def:"Reserved and saying very little.",ex:"He was taciturn during the meeting, offering few comments."},
      {w:"ubiquity",p:"noun",ipa:"/juːˈbɪkwɪti/",def:"The state of being everywhere at once.",ex:"The ubiquity of smartphones has changed daily habits."},
      {w:"vestige",p:"noun",ipa:"/ˈvɛstɪdʒ/",def:"A trace or remaining sign of something that once existed.",ex:"Only a vestige of the old castle wall remains."},
      {w:"winsome",p:"adjective",ipa:"/ˈwɪnsəm/",def:"Attractive or appealing in a charming way.",ex:"The child had a winsome smile."},
      {w:"zealot",p:"noun",ipa:"/ˈzɛlət/",def:"A person who is fanatically devoted to a cause.",ex:"He argued like a zealot, refusing to consider other views."},
      {w:"abstruse",p:"adjective",ipa:"/æbˈstruːs/",def:"Difficult to understand; obscure.",ex:"The professor's abstruse theory confused most students."}
    ]
  }
};
