window.VOCAB_DATA = {
  "0001": {
    slug: "agriculture",
    title: "Agriculture",
    desc: "Farming, food security, and the language of national agricultural policy — from staple crops to political will.",
    words: [
      {w:"self-sufficient",p:"adjective",ipa:"/ˌselfsəˈfɪʃənt/",def:"o'z-o'ziga yetarli / o'zini o'zi ta'minlay oladigan",ex:"The country aims to become self-sufficient in food production within a decade."},
      {w:"in terms of",p:"phrase",ipa:"/ɪn ˈtɜːmz əv/",def:"nuqtai nazaridan / jihatidan",ex:"In terms of cost, solar panels are becoming much more affordable."},
      {w:"staple crop",p:"noun",ipa:"/ˈsteɪpəl krɒp/",def:"asosiy oziq-ovqat ekini",ex:"Rice is the staple crop for millions of people across Asia."},
      {w:"corn",p:"noun",ipa:"/kɔːn/",def:"makkajo'xori (don)",ex:"Farmers harvested a large amount of corn this season."},
      {w:"maize",p:"noun",ipa:"/meɪz/",def:"makkajo'xori",ex:"Maize is widely grown across many African countries."},
      {w:"wheat",p:"noun",ipa:"/wiːt/",def:"bug'doy",ex:"Wheat is used to make bread and pasta."},
      {w:"go for",p:"phrasal verb",ipa:"/ɡəʊ fɔː/",def:"tanlamoq / afzal ko'rmoq",ex:"Many farmers decided to go for a more drought-resistant crop."},
      {w:"stick with",p:"phrasal verb",ipa:"/stɪk wɪð/",def:"sodiq qolmoq / davom ettirmoq",ex:"The government decided to stick with its original agricultural plan."},
      {w:"hand over",p:"phrasal verb",ipa:"/hænd ˈəʊvə/",def:"topshirmoq",ex:"Officials agreed to hand over control of the project to local farmers."},
      {w:"one and the same",p:"idiom",ipa:"/wʌn ənd ðə seɪm/",def:"aynan bir xil",ex:"For many people, these two issues are one and the same."},
      {w:"ambition",p:"noun",ipa:"/æmˈbɪʃən/",def:"maqsad / intilish",ex:"The country has a clear ambition to increase food production."},
      {w:"thinking big",p:"phrase",ipa:"/ˈθɪŋkɪŋ bɪɡ/",def:"katta o'ylash",ex:"Thinking big is essential when planning national development projects."},
      {w:"political will",p:"noun phrase",ipa:"/pəˈlɪtɪkəl wɪl/",def:"siyosiy iroda",ex:"Real change requires strong political will from the government."},
      {w:"accuse",p:"verb",ipa:"/əˈkjuːz/",def:"ayblamoq",ex:"Critics accuse the government of failing to support small farmers."},
      {w:"abundant",p:"adjective",ipa:"/əˈbʌndənt/",def:"mo'l-ko'l",ex:"The region has abundant rainfall throughout most of the year."},
      {w:"drought",p:"noun",ipa:"/draʊt/",def:"qurg'oqchilik",ex:"The drought severely affected crop production last year."},
      {w:"mechanise farms",p:"verb phrase",ipa:"/ˈmekənaɪz fɑːmz/",def:"fermer xo'jaliklarini mexanizatsiyalashtirmoq",ex:"The government plans to mechanise farms to increase efficiency."},
      {w:"embrace",p:"verb",ipa:"/ɪmˈbreɪs/",def:"qabul qilmoq / quchoq ochmoq",ex:"Many farmers are beginning to embrace new technology."},
      {w:"combat",p:"verb",ipa:"/ˈkɒmbæt/",def:"kurashmoq / qarshi kurash olib bormoq",ex:"New irrigation methods help combat the effects of drought."},
      {w:"trick question",p:"noun phrase",ipa:"/trɪk ˈkwestʃən/",def:"hiyla-nayrangli savol",ex:"That was a trick question, since both answers were technically correct."}
    ]
  },
  "0002": {
    slug: "tea-drinking-in-the-uk",
    title: "Tea Drinking in the UK",
    desc: "Britain's drinking culture — tea, coffee, pubs, and spirits, along with the language of habit, restraint, and excess.",
    words: [
      {w:"addict",p:"noun",ipa:"/ˈædɪkt/",def:"qaram / mukkasidan ketgan",ex:"He became an addict to caffeine after years of drinking coffee daily."},
      {w:"unremarkable",p:"adjective",ipa:"/ˌʌnrɪˈmɑːkəbəl/",def:"oddiy / e'tiborga sazovor bo'lmagan",ex:"The building looked completely unremarkable from the outside."},
      {w:"sweetened by",p:"phrase",ipa:"/ˈswiːtənd baɪ/",def:"...bilan shirin qilingan",ex:"The tea was sweetened by a spoonful of honey."},
      {w:"institution",p:"noun",ipa:"/ˌɪnstɪˈtjuːʃən/",def:"muassasa / an'ana",ex:"The pub has become a British institution over the centuries."},
      {w:"beer",p:"noun",ipa:"/bɪə/",def:"pivo",ex:"Many people enjoy a pint of beer after work."},
      {w:"port",p:"noun",ipa:"/pɔːt/",def:"port (spirtli ichimlik)",ex:"Port is a strong, sweet wine often served after dinner."},
      {w:"gin",p:"noun",ipa:"/dʒɪn/",def:"jin (spirtli ichimlik)",ex:"Gin is a popular spirit used in many cocktails."},
      {w:"ruling",p:"adjective",ipa:"/ˈruːlɪŋ/",def:"hukmron / boshqaruvchi",ex:"The ruling class had significant influence over public policy."},
      {w:"sobriety",p:"noun",ipa:"/səˈbraɪəti/",def:"hushyorlik",ex:"The campaign encourages sobriety among young drivers."},
      {w:"desire",p:"noun",ipa:"/dɪˈzaɪə/",def:"istak",ex:"There was a growing desire among workers for better wages."},
      {w:"sober",p:"adjective",ipa:"/ˈsəʊbə/",def:"hushyor",ex:"He stayed sober throughout the entire evening."},
      {w:"industrious",p:"adjective",ipa:"/ɪnˈdʌstriəs/",def:"mehnatkash / tirishqoq",ex:"The industrious workers finished the project ahead of schedule."},
      {w:"dissent",p:"noun",ipa:"/dɪˈsent/",def:"norozilik / e'tiroz",ex:"The government faced growing dissent over the new policy."},
      {w:"cappuccinos",p:"noun",ipa:"/ˌkæpuˈtʃiːnəʊz/",def:"kapuchinolar",ex:"The café is famous for its creamy cappuccinos."},
      {w:"lattes",p:"noun",ipa:"/ˈlɑːteɪz/",def:"lattelar",ex:"She ordered two lattes and a slice of cake."},
      {w:"staggering",p:"adjective",ipa:"/ˈstæɡərɪŋ/",def:"hayratlanarli darajada katta",ex:"The cost of the new stadium was staggering."},
      {w:"antiseptic",p:"noun",ipa:"/ˌæntɪˈseptɪk/",def:"antiseptik",ex:"The nurse cleaned the wound with antiseptic before bandaging it."}
    ]
  },
  "0003": {
    slug: "london-english",
    title: "London English",
    desc: "Cockney and East End dialect — rhyming slang, working-class heritage, and how London's voice keeps evolving.",
    words: [
      {w:"sensible",p:"adjective",ipa:"/ˈsensəbəl/",def:"oqilona",ex:"It's sensible to save some money each month."},
      {w:"exaggerated",p:"adjective",ipa:"/ɪɡˈzædʒəreɪtɪd/",def:"bo'rttirilgan",ex:"The reports of damage turned out to be exaggerated."},
      {w:"Bow",p:"noun",ipa:"/baʊ/",def:"Bou (London tumani)",ex:"Bow is a district in the East End of London."},
      {w:"Cockney",p:"noun",ipa:"/ˈkɒkni/",def:"kokni (London sharqi sheva va aholisi)",ex:"Cockney is a dialect traditionally spoken in the East End of London."},
      {w:"imagine",p:"verb",ipa:"/ɪˈmædʒɪn/",def:"tasavvur qilmoq",ex:"It's hard to imagine London without its famous accents."},
      {w:"evolving",p:"verb",ipa:"/ɪˈvɒlvɪŋ/",def:"rivojlanib boruvchi",ex:"The dialect has been evolving for centuries."},
      {w:"rhyming",p:"adjective",ipa:"/ˈraɪmɪŋ/",def:"qofiyalanuvchi",ex:"Cockney rhyming slang replaces words with rhyming phrases."},
      {w:"slang",p:"noun",ipa:"/slæŋ/",def:"sleng",ex:"Cockney slang is famous for its playful, hidden meanings."},
      {w:"dialect",p:"noun",ipa:"/ˈdaɪəlekt/",def:"sheva / dialekt",ex:"Cockney is one of London's most recognisable dialects."},
      {w:"mate",p:"noun",ipa:"/meɪt/",def:"do'st (norasmiy)",ex:"He greeted his old mate with a friendly handshake."},
      {w:"curator",p:"noun",ipa:"/kjʊˈreɪtə/",def:"kurator (muzey xodimi)",ex:"The museum curator explained the history behind each exhibit."},
      {w:"gradually",p:"adverb",ipa:"/ˈɡrædʒuəli/",def:"asta-sekin",ex:"The dialect has gradually changed over many generations."},
      {w:"descent",p:"noun",ipa:"/dɪˈsent/",def:"kelib chiqish / avlod",ex:"Many East End families are of working-class descent."},
      {w:"ruling-class",p:"noun",ipa:"/ˈruːlɪŋ klɑːs/",def:"hukmron sinf",ex:"The ruling-class often had very different customs from ordinary workers."},
      {w:"East Enders",p:"noun",ipa:"/iːst ˈendəz/",def:"Ist-Enderlar (London sharqi aholisi)",ex:"East Enders developed their own distinct way of speaking."},
      {w:"dig",p:"verb",ipa:"/dɪɡ/",def:"qazish",ex:"Workers had to dig deep trenches for the new pipeline."},
      {w:"grave",p:"noun",ipa:"/ɡreɪv/",def:"qabr",ex:"Cockney slang has its own particular word for a grave."},
      {w:"corned beef",p:"noun",ipa:"/kɔːnd biːf/",def:"konservalangan mol go'shti",ex:"Corned beef was a common meal among working-class families."},
      {w:"mi jam jar",p:"phrase",ipa:"/maɪ dʒæm dʒɑː/",def:"'mening mashinam' (kokni qofiyali slengi)",ex:"In Cockney rhyming slang, 'jam jar' can mean 'car'."},
      {w:"shirk",p:"verb",ipa:"/ʃɜːk/",def:"bo'yin tovlamoq / qochmoq",ex:"He tried to shirk his responsibilities at work."},
      {w:"shave",p:"verb",ipa:"/ʃeɪv/",def:"soqol olmoq",ex:"He decided to shave before the interview."},
      {w:"bizarre",p:"adjective",ipa:"/bɪˈzɑː/",def:"g'alati",ex:"Some of the rhyming slang terms sound completely bizarre at first."},
      {w:"here",p:"adverb",ipa:"/hɪə/",def:"bu yerda",ex:"Here, the dialect developed its own unique character."},
      {w:"sense of identity",p:"noun phrase",ipa:"/sens əv aɪˈdentəti/",def:"o'ziga xoslik hissi",ex:"The dialect gives East Enders a strong sense of identity."},
      {w:"delivering its services",p:"verb phrase",ipa:"/dɪˈlɪvərɪŋ ɪts ˈsɜːvɪsɪz/",def:"o'z xizmatlarini ko'rsatmoqda",ex:"The museum focuses on delivering its services to the local community."}
    ]
  },
  "0004": {
    slug: "the-london-tube",
    title: "The London Tube",
    desc: "Life on the London Underground — overcrowding, unreliability, and the sounds and habits of the daily commute.",
    words: [
      {w:"get around",p:"phrasal verb",ipa:"/ɡet əˈraʊnd/",def:"atrofda harakatlanmoq / borish-kelish qilmoq",ex:"Despite the constant delays, most Londoners still rely on public transport to get around the city efficiently."},
      {w:"the Tube",p:"noun",ipa:"/ðə tjuːb/",def:"metro (London metropoliteni)",ex:"Although the Tube can get unbearably crowded during rush hour, it remains the fastest way to cross London."},
      {w:"unreliable",p:"adjective",ipa:"/ˌʌnrɪˈlaɪəbəl/",def:"ishonchsiz",ex:"Commuters often complain that the service becomes increasingly unreliable whenever there's engineering work."},
      {w:"a love-hate relationship",p:"noun phrase",ipa:"/ə lʌv heɪt rɪˈleɪʃənʃɪp/",def:"sevgi-nafrat munosabati",ex:"Many residents have a love-hate relationship with the underground system, relying on it daily while constantly grumbling about it."},
      {w:"severe",p:"adjective",ipa:"/sɪˈvɪə/",def:"jiddiy / og'ir",ex:"Severe overcrowding on certain lines has prompted calls for significant investment in the network."},
      {w:"compartment",p:"noun",ipa:"/kəmˈpɑːtmənt/",def:"bo'lim / kupe",ex:"Passengers squeezed into every available compartment as the train pulled into the station."},
      {w:"armpit",p:"noun",ipa:"/ˈɑːmpɪt/",def:"qo'ltiq",ex:"During peak hours, you're practically pressed against a stranger's armpit, which hardly makes for a pleasant commute."},
      {w:"moon and back",p:"idiom",ipa:"/muːn ənd bæk/",def:"juda uzoq masofa (majoziy)",ex:"She joked that she'd travelled to the moon and back by the time she finally reached her stop."},
      {w:"get on with it",p:"idiom",ipa:"/ɡet ɒn wɪð ɪt/",def:"chidab, ishni davom ettirmoq",ex:"Rather than complaining, most passengers simply get on with it and accept the daily inconvenience."},
      {w:"squeeze into a carriage",p:"verb phrase",ipa:"/skwiːz ˈɪntuː ə ˈkærɪdʒ/",def:"vagonga zo'rg'a joylashib olmoq",ex:"Commuters had to squeeze into a carriage that was already packed well beyond capacity."},
      {w:"cramped",p:"adjective",ipa:"/kræmpt/",def:"tor / siqiq",ex:"The cramped conditions inside the carriage made it almost impossible to move, let alone read a newspaper."},
      {w:"eye contact",p:"noun phrase",ipa:"/aɪ ˈkɒntækt/",def:"ko'z bilan aloqa",ex:"Passengers deliberately avoid eye contact with one another, a habit that seems uniquely British."},
      {w:"poetic piece",p:"noun phrase",ipa:"/pəʊˈetɪk piːs/",def:"she'riy asar / lirik parcha",ex:"The documentary opened with a surprisingly poetic piece describing the rhythm of the city's commuters."},
      {w:"rumble",p:"noun",ipa:"/ˈrʌmbəl/",def:"gumburlash",ex:"The distant rumble of an approaching train signalled that the platform was about to fill with people."},
      {w:"clack",p:"noun",ipa:"/klæk/",def:"taqillash (temir yo'l tovushi)",ex:"The rhythmic clack of the wheels against the tracks became almost hypnotic after a while."},
      {w:"a constant soundtrack",p:"noun phrase",ipa:"/ə ˈkɒnstənt ˈsaʊndtræk/",def:"doimiy fon ovozi",ex:"The rumble and clack of the trains form a constant soundtrack to daily life in the city."},
      {w:"take for granted",p:"idiom",ipa:"/teɪk fɔː ˈɡrɑːntɪd/",def:"e'tiborsiz qoldirmoq / oddiy narsadek qabul qilmoq",ex:"It's easy to take the convenience of public transport for granted until it suddenly breaks down."},
      {w:"stomach",p:"verb",ipa:"/ˈstʌmək/",def:"chidamoq (fe'l ma'nosida)",ex:"Not everyone can stomach the discomfort of being squashed into a packed carriage every single morning."},
      {w:"vary",p:"verb",ipa:"/ˈveəri/",def:"farq qilmoq / o'zgarib turmoq",ex:"Waiting times can vary considerably depending on the time of day and which line you're using."},
      {w:"properly",p:"adverb",ipa:"/ˈprɒpəli/",def:"to'g'ri ravishda / yetarlicha",ex:"It's rare to get a seat and actually sit down properly during the morning rush."}
    ]
  },
  "0005": {
    slug: "who-does-the-housework",
    title: "Who Does the Housework",
    desc: "Chores, fairness, and the language of who really does what around the house.",
    words: [
      {w:"household chores",p:"noun phrase",ipa:"/ˈhaʊshəʊld tʃɔːz/",def:"uy yumushlari",ex:"Even in modern households, the distribution of household chores often still falls disproportionately on one partner."},
      {w:"fair share",p:"noun phrase",ipa:"/feə ʃeə/",def:"adolatli ulush",ex:"Many people feel they're doing more than their fair share of the housework, regardless of how equally tasks are actually divided."},
      {w:"worksheet",p:"noun",ipa:"/ˈwɜːkʃiːt/",def:"ish varag'i",ex:"The teacher handed out a worksheet designed to help students practise the new vocabulary in context."},
      {w:"conduct",p:"verb",ipa:"/kənˈdʌkt/",def:"o'tkazmoq (tadqiqot)",ex:"Researchers conducted a survey to find out how couples actually divide domestic responsibilities."},
      {w:"scrubbing the toilet",p:"verb phrase",ipa:"/ˈskrʌbɪŋ ðə ˈtɔɪlət/",def:"hojatxonani tozalash",ex:"Few people would volunteer for scrubbing the toilet, yet somebody in every household inevitably ends up doing it."},
      {w:"division of labour",p:"noun phrase",ipa:"/dɪˈvɪʒən əv ˈleɪbə/",def:"mehnat taqsimoti",ex:"The survey revealed some striking patterns in the division of labour between men and women at home."},
      {w:"sweep",p:"verb",ipa:"/swiːp/",def:"supurmoq",ex:"She would sweep the kitchen floor every evening before going to bed."},
      {w:"take a breather",p:"idiom",ipa:"/teɪk ə ˈbriːðə/",def:"tanaffus qilmoq",ex:"After finishing the ironing, he decided to take a breather before tackling the rest of the chores."},
      {w:"pulling their weight",p:"idiom",ipa:"/ˈpʊlɪŋ ðeə weɪt/",def:"o'z hissasini qo'shmoq",ex:"She complained that her flatmates weren't pulling their weight when it came to cleaning the shared kitchen."},
      {w:"to nag less",p:"phrase",ipa:"/tuː næɡ les/",def:"kamroq malomat qilish",ex:"Couples who divide chores more evenly tend to nag less about who's doing what."},
      {w:"apparently",p:"adverb",ipa:"/əˈpærəntli/",def:"shekilli / aftidan",ex:"Apparently, men are far more likely to underestimate the amount of housework they actually do."},
      {w:"reasonable amount",p:"noun phrase",ipa:"/ˈriːzənəbəl əˈmaʊnt/",def:"oqilona miqdor",ex:"As long as everyone contributes a reasonable amount, most people don't mind sharing the household duties."},
      {w:"stereotypically",p:"adverb",ipa:"/ˌsteriəˈtɪpɪkli/",def:"stereotipik ravishda",ex:"Cooking is stereotypically associated with women, even though attitudes have shifted considerably in recent decades."},
      {w:"once again",p:"phrase",ipa:"/wʌns əˈɡen/",def:"yana bir bor",ex:"Once again, the survey confirmed that domestic responsibilities are rarely divided completely equally."}
    ]
  },
  "0006": {
    slug: "estate-agents",
    title: "Estate Agents",
    desc: "The art of the property listing — how estate agents describe homes, and the language behind their glowing descriptions.",
    words: [
      {w:"descriptive",p:"adjective",ipa:"/dɪˈskrɪptɪv/",def:"tasviriy",ex:"Estate agents often rely on highly descriptive language to make even the smallest flat sound appealing."},
      {w:"characterful",p:"adjective",ipa:"/ˈkærɪktəfəl/",def:"o'ziga xos xarakterga ega",ex:"The old cottage had a characterful charm that modern, identical apartments simply couldn't replicate."},
      {w:"definitely",p:"adverb",ipa:"/ˈdefɪnətli/",def:"albatta / shubhasiz",ex:"The flat was definitely smaller than the photographs had suggested, despite the glowing description."},
      {w:"snatchers",p:"noun",ipa:"/ˈsnætʃəz/",def:"o'g'irlab ketuvchilar",ex:"The museum's exhibition explored the disturbing history of body snatchers who once stole corpses from graveyards."},
      {w:"cemetery",p:"noun",ipa:"/ˈsemətri/",def:"qabriston",ex:"The old cemetery on the edge of town dates back several centuries."},
      {w:"exclude",p:"verb",ipa:"/ɪkˈskluːd/",def:"chiqarib tashlamoq / istisno qilmoq",ex:"The listing conveniently excluded any mention of the noisy road right outside the bedroom window."},
      {w:"complicated",p:"adjective",ipa:"/ˈkɒmplɪkeɪtɪd/",def:"murakkab",ex:"Negotiating who does which chores can become surprisingly complicated once children are involved."},
      {w:"putting people off",p:"phrase",ipa:"/ˈpʊtɪŋ ˈpiːpəl ɒf/",def:"odamlarning hafsalasini pir qilish",ex:"The estate agent avoided mentioning the tiny kitchen for fear of putting people off."},
      {w:"compact",p:"adjective",ipa:"/kəmˈpækt/",def:"ixcham",ex:"The compact studio flat made clever use of every available inch of space."},
      {w:"bijou",p:"adjective",ipa:"/ˈbiːʒuː/",def:"juda kichik, ammo jozibali (uy haqida)",ex:"The advert described the flat as bijou, which usually turns out to be estate-agent code for extremely small."},
      {w:"panoramic",p:"adjective",ipa:"/ˌpænəˈræmɪk/",def:"panoramali",ex:"From the rooftop terrace, residents enjoy a genuinely panoramic view across the entire city skyline."},
      {w:"delightful",p:"adjective",ipa:"/dɪˈlaɪtfəl/",def:"ajoyib / yoqimli",ex:"The garden, though modest in size, was described as an absolutely delightful spot for morning coffee."},
      {w:"charming",p:"adjective",ipa:"/ˈtʃɑːmɪŋ/",def:"jozibali",ex:"The narrow, cobbled street gave the neighbourhood an undeniably charming, old-fashioned feel."},
      {w:"elegant",p:"adjective",ipa:"/ˈelɪɡənt/",def:"nafis",ex:"The building's elegant Victorian façade attracted buyers looking for something with genuine character."},
      {w:"poetic",p:"adjective",ipa:"/pəʊˈetɪk/",def:"she'riy",ex:"Some property descriptions read more like poetic prose than practical information about square footage."},
      {w:"poetry",p:"noun",ipa:"/ˈpəʊətri/",def:"she'riyat",ex:"Critics joked that certain estate agents write poetry rather than accurate descriptions of the properties."},
      {w:"factual",p:"adjective",ipa:"/ˈfæktʃuəl/",def:"faktik / haqiqiy ma'lumotga asoslangan",ex:"Buyers increasingly demand more factual, straightforward descriptions rather than flowery language."},
      {w:"appeal",p:"noun",ipa:"/əˈpiːl/",def:"jozibadorlik",ex:"The flat's main appeal lay in its unusually large windows, which flooded the rooms with natural light."},
      {w:"superb",p:"adjective",ipa:"/suːˈpɜːb/",def:"ajoyib",ex:"The estate agent praised the superb location, just a short walk from the station."},
      {w:"lead out onto",p:"phrasal verb",ipa:"/liːd aʊt ˈɒntuː/",def:"chiqib boradi",ex:"French doors in the living room lead out onto a small but sunny terrace."},
      {w:"terrace",p:"noun",ipa:"/ˈterəs/",def:"terrasa / ochiq maydoncha",ex:"They spent the whole summer evening relaxing on the terrace overlooking the garden."},
      {w:"beyond",p:"preposition",ipa:"/bɪˈjɒnd/",def:"narigi tomonda / undan tashqarida",ex:"Beyond the immediate neighbourhood, property prices dropped considerably."},
      {w:"breathe",p:"verb",ipa:"/briːð/",def:"nafas olmoq",ex:"After months of house-hunting in cramped flats, she finally found somewhere she could breathe."},
      {w:"treating",p:"verb",ipa:"/ˈtriːtɪŋ/",def:"munosabatda bo'lmoqda",ex:"The listing described the renovation as treating the original features with real care and respect."},
      {w:"jewel",p:"noun",ipa:"/ˈdʒuːəl/",def:"marvarid (majoziy)",ex:"The estate agent called the cottage a hidden jewel, tucked away at the end of a quiet lane."}
    ]
  }
};
