window.VOCAB_DATA = {
  "0001": {
    slug: "agriculture",
    title: "Agriculture",
    desc: "Farming, food security, and the language of national agricultural policy — from staple crops to political will.",
    words: [
      {w:"self-sufficient",p:"adjective",ipa:"/ˌselfsəˈfɪʃənt/",def:"o'z-o'ziga yetarli / o'zini o'zi ta'minlay oladigan",ex:"The country aims to become self-sufficient in food production within a decade."},
      {w:"in terms of",p:"phrase",ipa:"/ɪn ˈtɜːmz əv/",def:"nuqtai nazaridan / jihatidan",ex:"In terms of cost, solar panels are becoming much more affordable."},
      {w:"staple crop",p:"noun",ipa:"/ˈsteɪpəl krɒp/",def:"asosiy oziq-ovqat ekini",ex:"Rice is the staple crop for millions of people across Asia."},
      {w:"corn",p:"noun",ipa:"/kɔːn/",def:"makkajo'xori (don)",ex:"Farmers harvested a large amount of corn this season."},
      {w:"maize",p:"noun",ipa:"/meɪz/",def:"makkajo'xori",ex:"Maize is widely grown across many African countries."},
      {w:"wheat",p:"noun",ipa:"/wiːt/",def:"bug'doy",ex:"Wheat is used to make bread and pasta."},
      {w:"go for",p:"phrasal verb",ipa:"/ɡəʊ fɔː/",def:"tanlamoq / afzal ko'rmoq",ex:"Many farmers decided to go for a more drought-resistant crop."},
      {w:"stick with",p:"phrasal verb",ipa:"/stɪk wɪð/",def:"sodiq qolmoq / davom ettirmoq",ex:"The government decided to stick with its original agricultural plan."},
      {w:"hand over",p:"phrasal verb",ipa:"/hænd ˈəʊvə/",def:"topshirmoq",ex:"Officials agreed to hand over control of the project to local farmers."},
      {w:"one and the same",p:"idiom",ipa:"/wʌn ənd ðə seɪm/",def:"aynan bir xil",ex:"For many people, these two issues are one and the same."},
      {w:"ambition",p:"noun",ipa:"/æmˈbɪʃən/",def:"maqsad / intilish",ex:"The country has a clear ambition to increase food production."},
      {w:"thinking big",p:"phrase",ipa:"/ˈθɪŋkɪŋ bɪɡ/",def:"katta o'ylash",ex:"Thinking big is essential when planning national development projects."},
      {w:"political will",p:"noun phrase",ipa:"/pəˈlɪtɪkəl wɪl/",def:"siyosiy iroda",ex:"Real change requires strong political will from the government."},
      {w:"accuse",p:"verb",ipa:"/əˈkjuːz/",def:"ayblamoq",ex:"Critics accuse the government of failing to support small farmers."},
      {w:"abundant",p:"adjective",ipa:"/əˈbʌndənt/",def:"mo'l-ko'l",ex:"The region has abundant rainfall throughout most of the year."},
      {w:"drought",p:"noun",ipa:"/draʊt/",def:"qurg'oqchilik",ex:"The drought severely affected crop production last year."},
      {w:"mechanise farms",p:"verb phrase",ipa:"/ˈmekənaɪz fɑːmz/",def:"fermer xo'jaliklarini mexanizatsiyalashtirmoq",ex:"The government plans to mechanise farms to increase efficiency."},
      {w:"embrace",p:"verb",ipa:"/ɪmˈbreɪs/",def:"qabul qilmoq / quchoq ochmoq",ex:"Many farmers are beginning to embrace new technology."},
      {w:"combat",p:"verb",ipa:"/ˈkɒmbæt/",def:"kurashmoq / qarshi kurash olib bormoq",ex:"New irrigation methods help combat the effects of drought."},
      {w:"trick question",p:"noun phrase",ipa:"/trɪk ˈkwestʃən/",def:"hiyla-nayrangli savol",ex:"That was a trick question, since both answers were technically correct."}
    ]
  },
  "0002": {
    slug: "tea-drinking-in-the-uk",
    title: "Tea Drinking in the UK",
    desc: "Britain's drinking culture — tea, coffee, pubs, and spirits, along with the language of habit, restraint, and excess.",
    words: [
      {w:"addict",p:"noun",ipa:"/ˈædɪkt/",def:"qaram / mukkasidan ketgan",ex:"He became an addict to caffeine after years of drinking coffee daily."},
      {w:"unremarkable",p:"adjective",ipa:"/ˌʌnrɪˈmɑːkəbəl/",def:"oddiy / e'tiborga sazovor bo'lmagan",ex:"The building looked completely unremarkable from the outside."},
      {w:"sweetened by",p:"phrase",ipa:"/ˈswiːtənd baɪ/",def:"...bilan shirin qilingan",ex:"The tea was sweetened by a spoonful of honey."},
      {w:"institution",p:"noun",ipa:"/ˌɪnstɪˈtjuːʃən/",def:"muassasa / an'ana",ex:"The pub has become a British institution over the centuries."},
      {w:"beer",p:"noun",ipa:"/bɪə/",def:"pivo",ex:"Many people enjoy a pint of beer after work."},
      {w:"port",p:"noun",ipa:"/pɔːt/",def:"port (spirtli ichimlik)",ex:"Port is a strong, sweet wine often served after dinner."},
      {w:"gin",p:"noun",ipa:"/dʒɪn/",def:"jin (spirtli ichimlik)",ex:"Gin is a popular spirit used in many cocktails."},
      {w:"ruling",p:"adjective",ipa:"/ˈruːlɪŋ/",def:"hukmron / boshqaruvchi",ex:"The ruling class had significant influence over public policy."},
      {w:"sobriety",p:"noun",ipa:"/səˈbraɪəti/",def:"hushyorlik",ex:"The campaign encourages sobriety among young drivers."},
      {w:"desire",p:"noun",ipa:"/dɪˈzaɪə/",def:"istak",ex:"There was a growing desire among workers for better wages."},
      {w:"sober",p:"adjective",ipa:"/ˈsəʊbə/",def:"hushyor",ex:"He stayed sober throughout the entire evening."},
      {w:"industrious",p:"adjective",ipa:"/ɪnˈdʌstriəs/",def:"mehnatkash / tirishqoq",ex:"The industrious workers finished the project ahead of schedule."},
      {w:"dissent",p:"noun",ipa:"/dɪˈsent/",def:"norozilik / e'tiroz",ex:"The government faced growing dissent over the new policy."},
      {w:"cappuccinos",p:"noun",ipa:"/ˌkæpuˈtʃiːnəʊz/",def:"kapuchinolar",ex:"The café is famous for its creamy cappuccinos."},
      {w:"lattes",p:"noun",ipa:"/ˈlɑːteɪz/",def:"lattelar",ex:"She ordered two lattes and a slice of cake."},
      {w:"staggering",p:"adjective",ipa:"/ˈstæɡərɪŋ/",def:"hayratlanarli darajada katta",ex:"The cost of the new stadium was staggering."},
      {w:"antiseptic",p:"noun",ipa:"/ˌæntɪˈseptɪk/",def:"antiseptik",ex:"The nurse cleaned the wound with antiseptic before bandaging it."}
    ]
  },
  "0003": {
    slug: "london-english",
    title: "London English",
    desc: "Cockney and East End dialect — rhyming slang, working-class heritage, and how London's voice keeps evolving.",
    words: [
      {w:"sensible",p:"adjective",ipa:"/ˈsensəbəl/",def:"oqilona",ex:"It's sensible to save some money each month."},
      {w:"exaggerated",p:"adjective",ipa:"/ɪɡˈzædʒəreɪtɪd/",def:"bo'rttirilgan",ex:"The reports of damage turned out to be exaggerated."},
      {w:"Bow",p:"noun",ipa:"/baʊ/",def:"Bou (London tumani)",ex:"Bow is a district in the East End of London."},
      {w:"Cockney",p:"noun",ipa:"/ˈkɒkni/",def:"kokni (London sharqi sheva va aholisi)",ex:"Cockney is a dialect traditionally spoken in the East End of London."},
      {w:"imagine",p:"verb",ipa:"/ɪˈmædʒɪn/",def:"tasavvur qilmoq",ex:"It's hard to imagine London without its famous accents."},
      {w:"evolving",p:"verb",ipa:"/ɪˈvɒlvɪŋ/",def:"rivojlanib boruvchi",ex:"The dialect has been evolving for centuries."},
      {w:"rhyming",p:"adjective",ipa:"/ˈraɪmɪŋ/",def:"qofiyalanuvchi",ex:"Cockney rhyming slang replaces words with rhyming phrases."},
      {w:"slang",p:"noun",ipa:"/slæŋ/",def:"sleng",ex:"Cockney slang is famous for its playful, hidden meanings."},
      {w:"dialect",p:"noun",ipa:"/ˈdaɪəlekt/",def:"sheva / dialekt",ex:"Cockney is one of London's most recognisable dialects."},
      {w:"mate",p:"noun",ipa:"/meɪt/",def:"do'st (norasmiy)",ex:"He greeted his old mate with a friendly handshake."},
      {w:"curator",p:"noun",ipa:"/kjʊˈreɪtə/",def:"kurator (muzey xodimi)",ex:"The museum curator explained the history behind each exhibit."},
      {w:"gradually",p:"adverb",ipa:"/ˈɡrædʒuəli/",def:"asta-sekin",ex:"The dialect has gradually changed over many generations."},
      {w:"descent",p:"noun",ipa:"/dɪˈsent/",def:"kelib chiqish / avlod",ex:"Many East End families are of working-class descent."},
      {w:"ruling-class",p:"noun",ipa:"/ˈruːlɪŋ klɑːs/",def:"hukmron sinf",ex:"The ruling-class often had very different customs from ordinary workers."},
      {w:"East Enders",p:"noun",ipa:"/iːst ˈendəz/",def:"Ist-Enderlar (London sharqi aholisi)",ex:"East Enders developed their own distinct way of speaking."},
      {w:"dig",p:"verb",ipa:"/dɪɡ/",def:"qazish",ex:"Workers had to dig deep trenches for the new pipeline."},
      {w:"grave",p:"noun",ipa:"/ɡreɪv/",def:"qabr",ex:"Cockney slang has its own particular word for a grave."},
      {w:"corned beef",p:"noun",ipa:"/kɔːnd biːf/",def:"konservalangan mol go'shti",ex:"Corned beef was a common meal among working-class families."},
      {w:"mi jam jar",p:"phrase",ipa:"/maɪ dʒæm dʒɑː/",def:"'mening mashinam' (kokni qofiyali slengi)",ex:"In Cockney rhyming slang, 'jam jar' can mean 'car'."},
      {w:"shirk",p:"verb",ipa:"/ʃɜːk/",def:"bo'yin tovlamoq / qochmoq",ex:"He tried to shirk his responsibilities at work."},
      {w:"shave",p:"verb",ipa:"/ʃeɪv/",def:"soqol olmoq",ex:"He decided to shave before the interview."},
      {w:"bizarre",p:"adjective",ipa:"/bɪˈzɑː/",def:"g'alati",ex:"Some of the rhyming slang terms sound completely bizarre at first."},
      {w:"here",p:"adverb",ipa:"/hɪə/",def:"bu yerda",ex:"Here, the dialect developed its own unique character."},
      {w:"sense of identity",p:"noun phrase",ipa:"/sens əv aɪˈdentəti/",def:"o'ziga xoslik hissi",ex:"The dialect gives East Enders a strong sense of identity."},
      {w:"delivering its services",p:"verb phrase",ipa:"/dɪˈlɪvərɪŋ ɪts ˈsɜːvɪsɪz/",def:"o'z xizmatlarini ko'rsatmoqda",ex:"The museum focuses on delivering its services to the local community."}
    ]
  },
  "0004": {
    slug: "the-london-tube",
    title: "The London Tube",
    desc: "Life on the London Underground — overcrowding, unreliability, and the sounds and habits of the daily commute.",
    words: [
      {w:"get around",p:"phrasal verb",ipa:"/ɡet əˈraʊnd/",def:"atrofda harakatlanmoq / borish-kelish qilmoq",ex:"Despite the constant delays, most Londoners still rely on public transport to get around the city efficiently."},
      {w:"the Tube",p:"noun",ipa:"/ðə tjuːb/",def:"metro (London metropoliteni)",ex:"Although the Tube can get unbearably crowded during rush hour, it remains the fastest way to cross London."},
      {w:"unreliable",p:"adjective",ipa:"/ˌʌnrɪˈlaɪəbəl/",def:"ishonchsiz",ex:"Commuters often complain that the service becomes increasingly unreliable whenever there's engineering work."},
      {w:"a love-hate relationship",p:"noun phrase",ipa:"/ə lʌv heɪt rɪˈleɪʃənʃɪp/",def:"sevgi-nafrat munosabati",ex:"Many residents have a love-hate relationship with the underground system, relying on it daily while constantly grumbling about it."},
      {w:"severe",p:"adjective",ipa:"/sɪˈvɪə/",def:"jiddiy / og'ir",ex:"Severe overcrowding on certain lines has prompted calls for significant investment in the network."},
      {w:"compartment",p:"noun",ipa:"/kəmˈpɑːtmənt/",def:"bo'lim / kupe",ex:"Passengers squeezed into every available compartment as the train pulled into the station."},
      {w:"armpit",p:"noun",ipa:"/ˈɑːmpɪt/",def:"qo'ltiq",ex:"During peak hours, you're practically pressed against a stranger's armpit, which hardly makes for a pleasant commute."},
      {w:"moon and back",p:"idiom",ipa:"/muːn ənd bæk/",def:"juda uzoq masofa (majoziy)",ex:"She joked that she'd travelled to the moon and back by the time she finally reached her stop."},
      {w:"get on with it",p:"idiom",ipa:"/ɡet ɒn wɪð ɪt/",def:"chidab, ishni davom ettirmoq",ex:"Rather than complaining, most passengers simply get on with it and accept the daily inconvenience."},
      {w:"squeeze into a carriage",p:"verb phrase",ipa:"/skwiːz ˈɪntuː ə ˈkærɪdʒ/",def:"vagonga zo'rg'a joylashib olmoq",ex:"Commuters had to squeeze into a carriage that was already packed well beyond capacity."},
      {w:"cramped",p:"adjective",ipa:"/kræmpt/",def:"tor / siqiq",ex:"The cramped conditions inside the carriage made it almost impossible to move, let alone read a newspaper."},
      {w:"eye contact",p:"noun phrase",ipa:"/aɪ ˈkɒntækt/",def:"ko'z bilan aloqa",ex:"Passengers deliberately avoid eye contact with one another, a habit that seems uniquely British."},
      {w:"poetic piece",p:"noun phrase",ipa:"/pəʊˈetɪk piːs/",def:"she'riy asar / lirik parcha",ex:"The documentary opened with a surprisingly poetic piece describing the rhythm of the city's commuters."},
      {w:"rumble",p:"noun",ipa:"/ˈrʌmbəl/",def:"gumburlash",ex:"The distant rumble of an approaching train signalled that the platform was about to fill with people."},
      {w:"clack",p:"noun",ipa:"/klæk/",def:"taqillash (temir yo'l tovushi)",ex:"The rhythmic clack of the wheels against the tracks became almost hypnotic after a while."},
      {w:"a constant soundtrack",p:"noun phrase",ipa:"/ə ˈkɒnstənt ˈsaʊndtræk/",def:"doimiy fon ovozi",ex:"The rumble and clack of the trains form a constant soundtrack to daily life in the city."},
      {w:"take for granted",p:"idiom",ipa:"/teɪk fɔː ˈɡrɑːntɪd/",def:"e'tiborsiz qoldirmoq / oddiy narsadek qabul qilmoq",ex:"It's easy to take the convenience of public transport for granted until it suddenly breaks down."},
      {w:"stomach",p:"verb",ipa:"/ˈstʌmək/",def:"chidamoq (fe'l ma'nosida)",ex:"Not everyone can stomach the discomfort of being squashed into a packed carriage every single morning."},
      {w:"vary",p:"verb",ipa:"/ˈveəri/",def:"farq qilmoq / o'zgarib turmoq",ex:"Waiting times can vary considerably depending on the time of day and which line you're using."},
      {w:"properly",p:"adverb",ipa:"/ˈprɒpəli/",def:"to'g'ri ravishda / yetarlicha",ex:"It's rare to get a seat and actually sit down properly during the morning rush."}
    ]
  },
  "0005": {
    slug: "who-does-the-housework",
    title: "Who Does the Housework",
    desc: "Chores, fairness, and the language of who really does what around the house.",
    words: [
      {w:"household chores",p:"noun phrase",ipa:"/ˈhaʊshəʊld tʃɔːz/",def:"uy yumushlari",ex:"Even in modern households, the distribution of household chores often still falls disproportionately on one partner."},
      {w:"fair share",p:"noun phrase",ipa:"/feə ʃeə/",def:"adolatli ulush",ex:"Many people feel they're doing more than their fair share of the housework, regardless of how equally tasks are actually divided."},
      {w:"worksheet",p:"noun",ipa:"/ˈwɜːkʃiːt/",def:"ish varag'i",ex:"The teacher handed out a worksheet designed to help students practise the new vocabulary in context."},
      {w:"conduct",p:"verb",ipa:"/kənˈdʌkt/",def:"o'tkazmoq (tadqiqot)",ex:"Researchers conducted a survey to find out how couples actually divide domestic responsibilities."},
      {w:"scrubbing the toilet",p:"verb phrase",ipa:"/ˈskrʌbɪŋ ðə ˈtɔɪlət/",def:"hojatxonani tozalash",ex:"Few people would volunteer for scrubbing the toilet, yet somebody in every household inevitably ends up doing it."},
      {w:"division of labour",p:"noun phrase",ipa:"/dɪˈvɪʒən əv ˈleɪbə/",def:"mehnat taqsimoti",ex:"The survey revealed some striking patterns in the division of labour between men and women at home."},
      {w:"sweep",p:"verb",ipa:"/swiːp/",def:"supurmoq",ex:"She would sweep the kitchen floor every evening before going to bed."},
      {w:"take a breather",p:"idiom",ipa:"/teɪk ə ˈbriːðə/",def:"tanaffus qilmoq",ex:"After finishing the ironing, he decided to take a breather before tackling the rest of the chores."},
      {w:"pulling their weight",p:"idiom",ipa:"/ˈpʊlɪŋ ðeə weɪt/",def:"o'z hissasini qo'shmoq",ex:"She complained that her flatmates weren't pulling their weight when it came to cleaning the shared kitchen."},
      {w:"to nag less",p:"phrase",ipa:"/tuː næɡ les/",def:"kamroq malomat qilish",ex:"Couples who divide chores more evenly tend to nag less about who's doing what."},
      {w:"apparently",p:"adverb",ipa:"/əˈpærəntli/",def:"shekilli / aftidan",ex:"Apparently, men are far more likely to underestimate the amount of housework they actually do."},
      {w:"reasonable amount",p:"noun phrase",ipa:"/ˈriːzənəbəl əˈmaʊnt/",def:"oqilona miqdor",ex:"As long as everyone contributes a reasonable amount, most people don't mind sharing the household duties."},
      {w:"stereotypically",p:"adverb",ipa:"/ˌsteriəˈtɪpɪkli/",def:"stereotipik ravishda",ex:"Cooking is stereotypically associated with women, even though attitudes have shifted considerably in recent decades."},
      {w:"once again",p:"phrase",ipa:"/wʌns əˈɡen/",def:"yana bir bor",ex:"Once again, the survey confirmed that domestic responsibilities are rarely divided completely equally."}
    ]
  },
  "0006": {
    slug: "estate-agents",
    title: "Estate Agents",
    desc: "The art of the property listing — how estate agents describe homes, and the language behind their glowing descriptions.",
    words: [
      {w:"descriptive",p:"adjective",ipa:"/dɪˈskrɪptɪv/",def:"tasviriy",ex:"Estate agents often rely on highly descriptive language to make even the smallest flat sound appealing."},
      {w:"characterful",p:"adjective",ipa:"/ˈkærɪktəfəl/",def:"o'ziga xos xarakterga ega",ex:"The old cottage had a characterful charm that modern, identical apartments simply couldn't replicate."},
      {w:"definitely",p:"adverb",ipa:"/ˈdefɪnətli/",def:"albatta / shubhasiz",ex:"The flat was definitely smaller than the photographs had suggested, despite the glowing description."},
      {w:"snatchers",p:"noun",ipa:"/ˈsnætʃəz/",def:"o'g'irlab ketuvchilar",ex:"The museum's exhibition explored the disturbing history of body snatchers who once stole corpses from graveyards."},
      {w:"cemetery",p:"noun",ipa:"/ˈsemətri/",def:"qabriston",ex:"The old cemetery on the edge of town dates back several centuries."},
      {w:"exclude",p:"verb",ipa:"/ɪkˈskluːd/",def:"chiqarib tashlamoq / istisno qilmoq",ex:"The listing conveniently excluded any mention of the noisy road right outside the bedroom window."},
      {w:"complicated",p:"adjective",ipa:"/ˈkɒmplɪkeɪtɪd/",def:"murakkab",ex:"Negotiating who does which chores can become surprisingly complicated once children are involved."},
      {w:"putting people off",p:"phrase",ipa:"/ˈpʊtɪŋ ˈpiːpəl ɒf/",def:"odamlarning hafsalasini pir qilish",ex:"The estate agent avoided mentioning the tiny kitchen for fear of putting people off."},
      {w:"compact",p:"adjective",ipa:"/kəmˈpækt/",def:"ixcham",ex:"The compact studio flat made clever use of every available inch of space."},
      {w:"bijou",p:"adjective",ipa:"/ˈbiːʒuː/",def:"juda kichik, ammo jozibali (uy haqida)",ex:"The advert described the flat as bijou, which usually turns out to be estate-agent code for extremely small."},
      {w:"panoramic",p:"adjective",ipa:"/ˌpænəˈræmɪk/",def:"panoramali",ex:"From the rooftop terrace, residents enjoy a genuinely panoramic view across the entire city skyline."},
      {w:"delightful",p:"adjective",ipa:"/dɪˈlaɪtfəl/",def:"ajoyib / yoqimli",ex:"The garden, though modest in size, was described as an absolutely delightful spot for morning coffee."},
      {w:"charming",p:"adjective",ipa:"/ˈtʃɑːmɪŋ/",def:"jozibali",ex:"The narrow, cobbled street gave the neighbourhood an undeniably charming, old-fashioned feel."},
      {w:"elegant",p:"adjective",ipa:"/ˈelɪɡənt/",def:"nafis",ex:"The building's elegant Victorian façade attracted buyers looking for something with genuine character."},
      {w:"poetic",p:"adjective",ipa:"/pəʊˈetɪk/",def:"she'riy",ex:"Some property descriptions read more like poetic prose than practical information about square footage."},
      {w:"poetry",p:"noun",ipa:"/ˈpəʊətri/",def:"she'riyat",ex:"Critics joked that certain estate agents write poetry rather than accurate descriptions of the properties."},
      {w:"factual",p:"adjective",ipa:"/ˈfæktʃuəl/",def:"faktik / haqiqiy ma'lumotga asoslangan",ex:"Buyers increasingly demand more factual, straightforward descriptions rather than flowery language."},
      {w:"appeal",p:"noun",ipa:"/əˈpiːl/",def:"jozibadorlik",ex:"The flat's main appeal lay in its unusually large windows, which flooded the rooms with natural light."},
      {w:"superb",p:"adjective",ipa:"/suːˈpɜːb/",def:"ajoyib",ex:"The estate agent praised the superb location, just a short walk from the station."},
      {w:"lead out onto",p:"phrasal verb",ipa:"/liːd aʊt ˈɒntuː/",def:"chiqib boradi",ex:"French doors in the living room lead out onto a small but sunny terrace."},
      {w:"terrace",p:"noun",ipa:"/ˈterəs/",def:"terrasa / ochiq maydoncha",ex:"They spent the whole summer evening relaxing on the terrace overlooking the garden."},
      {w:"beyond",p:"preposition",ipa:"/bɪˈjɒnd/",def:"narigi tomonda / undan tashqarida",ex:"Beyond the immediate neighbourhood, property prices dropped considerably."},
      {w:"breathe",p:"verb",ipa:"/briːð/",def:"nafas olmoq",ex:"After months of house-hunting in cramped flats, she finally found somewhere she could breathe."},
      {w:"treating",p:"verb",ipa:"/ˈtriːtɪŋ/",def:"munosabatda bo'lmoqda",ex:"The listing described the renovation as treating the original features with real care and respect."},
      {w:"jewel",p:"noun",ipa:"/ˈdʒuːəl/",def:"marvarid (majoziy)",ex:"The estate agent called the cottage a hidden jewel, tucked away at the end of a quiet lane."}
    ]
  },
  "0007": {
    slug: "men-are-the-weaker-sex",
    title: "Men Are the Weaker Sex",
    desc: "Men's health, denial, and vulnerability — why men are often slower to admit something is wrong.",
    words: [
      {w:"supposedly",p:"adverb",ipa:"/səˈpəʊzɪdli/",def:"used to refer to something that is generally assumed or claimed to be true, although perhaps it is not",tr:"taxminan / go'yoki (aslida unchalik ham emas)",ex:"Men are supposedly far less likely than women to book a doctor's appointment for a minor symptom."},
      {w:"ten-fold",p:"adverb",ipa:"/ˈtenfəʊld/",def:"by ten times as much or as many",tr:"o'n baravar",ex:"His risk of a second heart attack increased ten-fold once he ignored his doctor's advice and went back to smoking."},
      {w:"tablet",p:"noun",ipa:"/ˈtæblɪt/",def:"a small, solid, round or oval mass of a drug or medicine that is swallowed whole",tr:"tabletka (dori)",ex:"He's supposed to take a tablet every morning to keep his blood pressure under control."},
      {w:"angina",p:"noun",ipa:"/ænˈdʒaɪnə/",def:"a heart condition that causes sudden pain in the chest, usually because the heart is not getting enough blood",tr:"stenokardiya / yurak og'rig'i",ex:"He'd been suffering from angina for months before he finally admitted something was wrong."},
      {w:"so forth",p:"phrase",ipa:"/səʊ ˈfɔːθ/",def:"used after a list to show that other similar things could also be mentioned",tr:"va hokazo",ex:"The survey covered diet, exercise, sleeping habits, and so forth."},
      {w:"fuss",p:"noun",ipa:"/fʌs/",def:"unnecessary or excessive excitement, activity, or concern about something",tr:"ortiqcha tashvish / g'alva",ex:"He waved off the chest pain, insisting he didn't want to make a fuss over nothing."},
      {w:"burden",p:"noun",ipa:"/ˈbɜːdn/",def:"a heavy load, or something that causes difficulty, worry, or hard work",tr:"yuk / og'irlik (majoziy)",ex:"Untreated illness can quickly become a financial burden for the whole family."},
      {w:"commit",p:"verb",ipa:"/kəˈmɪt/",def:"to bind yourself to a particular course of action, or promise to do something seriously",tr:"o'zini bag'ishlamoq / va'da bermoq",ex:"It took a health scare before he was willing to commit to a healthier lifestyle."},
      {w:"to draw any attention",p:"phrase",ipa:"/tuː drɔː ˈeni əˈtenʃən/",def:"to make people notice something, often used with a negative to describe avoiding notice",tr:"e'tiborni tortmoq",ex:"He kept quiet about his symptoms at work, not wanting to draw any attention to himself."},
      {w:"nuisance",p:"noun",ipa:"/ˈnjuːsns/",def:"a person, thing, or situation that causes trouble, annoyance, or inconvenience",tr:"bezovtalik / halaqit beruvchi narsa",ex:"Plenty of men regard a routine check-up as more of a nuisance than a necessity."},
      {w:"to use up",p:"phrasal verb",ipa:"/tuː juːz ʌp/",def:"to consume the whole of something, so that none is left",tr:"sarflab tugatmoq",ex:"Delaying treatment can use up valuable time that doctors need to intervene effectively."},
      {w:"lifestyle choices",p:"noun phrase",ipa:"/ˈlaɪfstaɪl tʃɔɪsɪz/",def:"the decisions a person makes about how they live, such as what they eat, how active they are, and their habits",tr:"turmush tarzi tanlovlari",ex:"Poor lifestyle choices, including smoking and a lack of exercise, remain leading causes of heart disease in men."},
      {w:"charity",p:"noun",ipa:"/ˈtʃærəti/",def:"an organisation set up to provide help and raise money for people in need",tr:"xayriya tashkiloti",ex:"The men's health charity launched a campaign urging men to get symptoms checked earlier."},
      {w:"stuck",p:"adjective",ipa:"/stʌk/",def:"unable to move, change, or make progress in a particular situation",tr:"qotib qolgan / harakatsiz",ex:"He felt stuck, reluctant to admit that something might seriously be wrong with his health."},
      {w:"admit",p:"verb",ipa:"/ədˈmɪt/",def:"to accept, often reluctantly, that something unwelcome is true",tr:"tan olmoq / e'tirof etmoq",ex:"It took him several months to finally admit that he needed to see a specialist."},
      {w:"vulnerability",p:"noun",ipa:"/ˌvʌlnərəˈbɪləti/",def:"the quality of being easily physically or emotionally hurt, or open to attack or harm",tr:"zaiflik / himoyasizlik",ex:"Talking openly about vulnerability is still something many men find genuinely difficult."},
      {w:"aware",p:"adjective",ipa:"/əˈweə(r)/",def:"having knowledge of a situation or fact; conscious of something",tr:"xabardor / ogoh",ex:"Campaigners want more men to become aware of the early warning signs of heart disease."},
      {w:"accessible",p:"adjective",ipa:"/əkˈsesəbl/",def:"able to be reached, entered, used, or understood easily",tr:"foydalanish oson / qulay",ex:"Health services need to be made more accessible to men who work long or irregular hours."}
    ]
  },
  "0008": {
    slug: "media-blackout",
    title: "Media Blackout",
    desc: "Digital detox and disconnecting from screens — what happens to attention, mood, and habits when the media stops.",
    words: [
      {w:"media blackout",p:"noun phrase",ipa:"/ˈmiːdiə ˈblækaʊt/",def:"a period during which someone deliberately avoids all forms of media, such as news, television, or social media",tr:"ommaviy axborot vositalaridan vaqtincha voz kechish",ex:"She committed to a two-week media blackout to see whether it would improve her concentration."},
      {w:"unplugged",p:"adjective",ipa:"/ʌnˈplʌɡd/",def:"not connected to an electrical supply; informally, disconnected from phones, computers, and other devices",tr:"ulanmagan / texnologiyadan uzilgan",ex:"He spent the entire weekend unplugged, with his phone switched off in a drawer."},
      {w:"seem",p:"verb",ipa:"/siːm/",def:"to give the impression of being or doing something; to appear to be true",tr:"tuyulmoq / ko'rinmoq",ex:"Giving up social media for a week didn't seem like a big deal until she actually tried it."},
      {w:"guinea pig",p:"noun",ipa:"/ˈɡɪni pɪɡ/",def:"a person used as the subject of an experiment, especially one that is new or untested",tr:"tajriba quyoni (majoziy: sinov predmeti)",ex:"Twenty volunteers acted as guinea pigs for the university's digital detox study."},
      {w:"furry",p:"adjective",ipa:"/ˈfɜːri/",def:"covered with fur; having a soft, fur-like texture",tr:"mo'ynali / junli",ex:"The stress ball on her desk was small, furry, and completely useless once her phone was taken away."},
      {w:"short-eared rabbit",p:"noun phrase",ipa:"/ʃɔːt ɪəd ˈræbɪt/",def:"a breed of rabbit distinguished by unusually short ears",tr:"qisqa quloqli quyon",ex:"As part of the experiment, participants were given a short-eared rabbit to care for instead of checking their phones."},
      {w:"literally",p:"adverb",ipa:"/ˈlɪtərəli/",def:"in a literal or exact sense; used for emphasis, though not always technically accurate",tr:"so'zma-so'z / haqiqatan ham",ex:"By day three, she was literally counting the minutes until she could check her messages again."},
      {w:"affect",p:"verb",ipa:"/əˈfekt/",def:"to have an influence on someone or something, or to cause a change in it",tr:"ta'sir qilmoq",ex:"Researchers found that constant notifications can seriously affect a person's ability to concentrate."},
      {w:"mental well-being",p:"noun phrase",ipa:"/ˈmentl wel ˈbiːɪŋ/",def:"a person's psychological and emotional health and happiness",tr:"ruhiy salomatlik",ex:"Excessive screen time has been linked to a decline in teenagers' mental well-being."},
      {w:"withdrawal symptoms",p:"noun phrase",ipa:"/wɪðˈdrɔːəl ˈsɪmptəmz/",def:"unpleasant physical or psychological effects that occur when someone stops a habitual activity or substance",tr:"tark etish alomatlari",ex:"Several participants reported withdrawal symptoms, including anxiety and restlessness, within the first two days."},
      {w:"detached",p:"adjective",ipa:"/dɪˈtætʃt/",def:"not emotionally involved; separated or distant from something",tr:"ajralgan / begonalashgan",ex:"Without her phone constantly in hand, she felt oddly detached from her usual daily routine."},
      {w:"isolate",p:"verb",ipa:"/ˈaɪsəleɪt/",def:"to cause a person or thing to be or feel alone or separated from others",tr:"ajratmoq / yakkalantirmoq",ex:"Ironically, constant scrolling can isolate people from the face-to-face relationships they value most."},
      {w:"long-term effects",p:"noun phrase",ipa:"/lɒŋ tɜːm ɪˈfekts/",def:"consequences of something that continue to be felt over an extended period of time",tr:"uzoq muddatli ta'sirlar",ex:"Scientists are still investigating the long-term effects of heavy social media use on young people's brains."},
      {w:"afterwards",p:"adverb",ipa:"/ˈɑːftəwədz/",def:"after the time or event that has just been mentioned",tr:"keyinchalik / undan keyin",ex:"She admitted that, afterwards, she felt noticeably calmer and more focused than before the blackout."},
      {w:"waking hours",p:"noun phrase",ipa:"/ˈweɪkɪŋ ˈaʊəz/",def:"the part of the day when a person is awake, as opposed to asleep",tr:"uyg'oq vaqt (kun davomida)",ex:"He was shocked to realise he spent almost all of his waking hours looking at a screen."},
      {w:"permanent",p:"adjective",ipa:"/ˈpɜːmənənt/",def:"lasting or intended to last indefinitely; not temporary",tr:"doimiy / o'zgarmas",ex:"The experiment convinced her to make some permanent changes to her phone habits."},
      {w:"reminder",p:"noun",ipa:"/rɪˈmaɪndə(r)/",def:"something that causes a person to remember something",tr:"eslatma",ex:"The blank, silent screen served as a constant reminder of how dependent she'd become on it."},
      {w:"help us out with",p:"phrasal verb",ipa:"/help ʌs aʊt wɪð/",def:"to assist someone in dealing with or completing a task",tr:"...da yordam bermoq",ex:"We're recruiting more volunteers to help us out with the next stage of the study."}
    ]
  },
  "0009": {
    slug: "dress-codes-what-can-you-wear",
    title: "Dress Codes: What Can You Wear",
    desc: "Formal wear, workplace rules, and the unwritten codes that decide what's considered acceptable to wear.",
    words: [
      {w:"dinner jacket",p:"noun",ipa:"/ˈdɪnə dʒækɪt/",def:"(British English) a black jacket, usually worn with a bow tie, for formal evening occasions; called a tuxedo in American English",tr:"smoking (rasmiy kechki kostyum)",ex:"Guests attending the charity gala were asked to wear a dinner jacket."},
      {w:"dress up",p:"phrasal verb",ipa:"/dres ʌp/",def:"to put on formal, smart, or more elaborate clothes than usual",tr:"yasan-tusan qilmoq / rasmiy kiyinmoq",ex:"Staff were encouraged to dress up for the company's annual awards dinner."},
      {w:"wardrobe",p:"noun",ipa:"/ˈwɔːdrəʊb/",def:"a person's entire collection of clothes, or a large piece of furniture for storing clothes",tr:"kiyimlar to'plami / shkaf",ex:"Her work wardrobe was carefully chosen to fit the firm's conservative dress code."},
      {w:"smart casual",p:"noun phrase",ipa:"/smɑːt ˈkæʒuəl/",def:"a style of dress that is neat and reasonably conventional but not as formal as business wear",tr:"yarim norasmiy uslub",ex:"Since the invitation said smart casual, he wore a blazer with no tie."},
      {w:"marching order",p:"noun phrase",ipa:"/ˈmɑːtʃɪŋ ˈɔːdə(r)/",def:"(informal) an instruction to leave immediately, or a firm instruction to do something without delay",tr:"jo'nash buyrug'i / ketish ko'rsatmasi",ex:"New recruits were given their marching orders on the very first morning of training."},
      {w:"gone are the flashy",p:"phrase",ipa:"/ɡɒn ɑː ðə ˈflæʃi/",def:"used to say that something showy or ostentatious is no longer fashionable or considered acceptable",tr:"\"ko'zga tashlanadigan narsalar o'tmishda qoldi\" iborasi",ex:"Gone are the flashy ties of the 1980s; today's boardrooms favour understated, muted colours."},
      {w:"provocative",p:"adjective",ipa:"/prəˈvɒkətɪv/",def:"intended to provoke a strong reaction, or, of clothing, intended to arouse sexual interest",tr:"his-tuyg'uni qo'zg'atuvchi / dag'al ta'sir qiluvchi",ex:"Several schools have introduced rules against clothing they consider too provocative."},
      {w:"subdued",p:"adjective",ipa:"/səbˈdjuːd/",def:"quiet, restrained, and not bright or intense",tr:"xira / bosiq (rang haqida)",ex:"The office dress code calls for subdued colours rather than bold patterns."},
      {w:"scent",p:"noun",ipa:"/sent/",def:"a distinctive smell, especially a pleasant one, or a perfume",tr:"hid / atir hidi",ex:"A light scent of perfume is usually fine, but strong fragrances are discouraged in shared offices."},
      {w:"sharp aroma",p:"noun phrase",ipa:"/ʃɑːp əˈrəʊmə/",def:"a strong, distinct, and noticeable smell",tr:"keskin / o'tkir hid",ex:"The sharp aroma of his cologne lingered in the meeting room long after he had left."},
      {w:"revealing",p:"adjective",ipa:"/rɪˈviːlɪŋ/",def:"(of clothing) allowing a great deal of the body to be seen",tr:"ochiq (kiyim haqida)",ex:"The company guidelines discourage clothing that staff or clients might consider too revealing."},
      {w:"cleavage",p:"noun",ipa:"/ˈkliːvɪdʒ/",def:"the space between a woman's breasts, especially as shown by a low-cut garment",tr:"ko'krak orasi (dekolte)",ex:"The dress-code memo specifically noted that excessive cleavage was not appropriate in client meetings."},
      {w:"flats",p:"noun",ipa:"/flæts/",def:"shoes with flat soles and no heel, or a very low heel",tr:"taqsimli poshnasiz oyoq kiyim",ex:"She swapped her heels for flats halfway through the long day of back-to-back meetings."},
      {w:"high heel",p:"noun",ipa:"/haɪ hiːl/",def:"a shoe with a tall, narrow heel",tr:"baland poshnali poyabzal",ex:"Several companies have faced criticism for requiring female employees to wear high heels."},
      {w:"break across",p:"phrase",ipa:"/breɪk əˈkrɒs/",def:"the point at which an item of clothing, such as a trouser leg or sleeve, meets or falls against another part of the body",tr:"kiyimning tana qismiga tegib turishi",ex:"A well-tailored jacket sleeve should break across the wrist rather than the palm."},
      {w:"suit sleeves",p:"noun phrase",ipa:"/suːt sliːvz/",def:"the sleeves of a suit jacket",tr:"kostyum yengi",ex:"Tailors generally recommend that suit sleeves end just above the wrist bone."},
      {w:"palm",p:"noun",ipa:"/pɑːm/",def:"the inner surface of the hand, between the wrist and the fingers",tr:"kaft",ex:"He nervously wiped his palm on his trousers before shaking hands at the interview."},
      {w:"colonial",p:"adjective",ipa:"/kəˈləʊniəl/",def:"relating to a colony, or to a period or system of colonial rule",tr:"mustamlakachilik davriga oid",ex:"The exhibition examined how colonial-era fashion continues to influence modern formal dress."}
    ]
  },
  "0010": {
    slug: "black-history-month",
    title: "Black History Month",
    desc: "How societies discuss race, history, and slavery — and why the conversation is often a difficult one.",
    words: [
      {w:"rather",p:"adverb",ipa:"/ˈrɑːðə(r)/",def:"to a noticeable or significant extent; fairly or quite",tr:"ancha / birmuncha",ex:"The proposal to revise the curriculum sparked rather more controversy than the organisers had anticipated."},
      {w:"heated debate",p:"noun phrase",ipa:"/ˈhiːtɪd dɪˈbeɪt/",def:"an argument or discussion carried out with strong emotion, and sometimes anger",tr:"qizg'in bahs",ex:"The question of how slavery should be taught in schools led to a heated debate among parents and teachers."},
      {w:"ideally",p:"adverb",ipa:"/aɪˈdiːəli/",def:"in an ideal or perfect situation; if everything happened exactly as one would wish",tr:"ideal holatda",ex:"Ideally, Black History Month would encourage reflection throughout the whole year, not just in October."},
      {w:"slavery",p:"noun",ipa:"/ˈsleɪvəri/",def:"the state of being legally owned by another person and forced to work for them; the practice of owning slaves",tr:"qullik",ex:"The museum's new exhibition traces the history of slavery and its lasting impact on modern society."},
      {w:"wherever",p:"adverb",ipa:"/weərˈevə(r)/",def:"in, at, or to whatever place",tr:"qayerda bo'lmasin",ex:"Organisers hope the campaign's message will reach people wherever they happen to encounter it."},
      {w:"My goodness",p:"exclamation",ipa:"/maɪ ˈɡʊdnəs/",def:"used to express surprise, shock, or astonishment",tr:"\"Voy xudoyim!\" (hayratlanish undovi)",ex:"My goodness, I had no idea this part of the country's history had been left out of the textbooks for so long."}
    ]
  }
};
